from mashine.Car import Car
from mashine.Car_Type import Car_Type

noname = Car("From Factory")
print(noname.class_name + " " + noname.car_name)
noname.drive()
noname.repair()
print(noname.breaking)

lada = Car_Type("lada")
print(lada.car_name + " " + lada.class_name)
lada.drive()
lada.repair()
print(lada.engine)
print(lada.shassis)
print(lada.transmission)
lada.change_assembly("diesel", "front_wheel", "manual")
lada.drive()
print(lada.engine)
print(lada.shassis)
print(lada.transmission)
#lada.repair()
print(lada.weight_over_3_tons)
lada.can_transport()
#print(lada.body)
#print(lada.engine)
#print(lada.shassis)
#print(lada.transmission)


kamaz = Car_Type("Kamaz")
kamaz.change_class_type("Cargo")
print(kamaz.car_name + " " + kamaz.class_name)
kamaz.change_assembly("diesel", "six_wheel", "manual")
kamaz.change_weight(True)
kamaz.drive()
kamaz.repair()
#kamaz.repair()
print(kamaz.weight_over_3_tons)
kamaz.can_transport()
print(kamaz.body)
print(kamaz.engine)
print(kamaz.shassis)
print(kamaz.transmission)
##kamaz.change_color("Orange")
