from mashine.car import Car
from mashine.Cargo import Cargo
from mashine.Passenger import Passengers

noname = Car("From Factory")
print(noname.class_name + " " + noname.car_name)
noname.drive()

lada = Passengers("lada")
print(lada.car_name + " " + lada.class_name)
lada.drive()
lada.can_transport_cargo()
lada.can_transport_passengers()
print(lada.body)
print(lada.engine)
print(lada.shassis)
print(lada.transmission)
lada.change_assembly("Gas", "back_wheel", "auto")
print(lada.engine)
print(lada.shassis)
print(lada.transmission)
lada.change_transporting_type("Cargo")
print(lada.body)
lada.color("red")
print(lada.weight_over_3_tons)
lada.change_weight(True)
print(lada.weight_over_3_tons)
lada.can_transport_cargo()
lada.can_transport_passengers()

kamaz = Cargo("Kamaz")
print(kamaz.car_name + " " + kamaz.class_name)
kamaz.drive()
kamaz.can_transport_cargo()
kamaz.can_transport_passengers()
print(kamaz.body)
print(kamaz.engine)
print(kamaz.shassis)
print(kamaz.transmission)
print(kamaz.min)
print(kamaz.max)
kamaz.color("Orange")
print(kamaz.weight_over_3_tons)